# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  make:
    name: Build Tweak
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install ldid and xz
        run: |
          brew install ldid xz
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app 
      - name: Setup Theos
        uses: actions/checkout@master
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Download SDKs
        run: |
          curl -LO https://github.com/SamHep0803/iOS-13-Patched-SDK/archive/master.zip
          TMP=$(mktemp -d)
          unzip master.zip -d $TMP
          mv $TMP/iOS-13-Patched-SDK-master/*.sdk theos/sdks
          rm -r master.zip $TMP
      - name: Build Tweak
        id: build
        run: |
         make clean package FINALPACKAGE=1
         echo "::set-output name=package::$(ls -t packages | head -n1)"
